package de.greenrobot.daoexample;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PP".
 */
public class PP {

    private Long id;
    /** Not-null value. */
    private String text;
    private String psw;
    private java.util.Date date;

    public PP() {
    }

    public PP(Long id) {
        this.id = id;
    }

    public PP(Long id, String text, String psw, java.util.Date date) {
        this.id = id;
        this.text = text;
        this.psw = psw;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getText() {
        return text;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setText(String text) {
        this.text = text;
    }

    public String getPsw() {
        return psw;
    }

    public void setPsw(String psw) {
        this.psw = psw;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

}
